// Package static embeds the browser assets and serves them under /static/.
//
// Vendored files (committed, no Node and no CDN at runtime): htmx.min.js is htmx
// 2.0.11 dist/htmx.min.js (unpkg.com/htmx.org@2.0.11), alpine.min.js is alpinejs
// 3.17.4 dist/cdn.min.js (jsdelivr), and fonts/ holds the latin subset of IBM Plex
// Sans (400/500/600) and Mono (400/500) from @fontsource. R-DEP-10 suggested
// hash-pinned fetchurl in Nix; committing the files is the chosen simpler path,
// so a version bump is a file replacement in a reviewed commit.
//
// app.css is generated by `just assets` (Tailwind) and gitignored. The embed
// patterns below match theme.css and input.css even when app.css is absent, so
// the build and tests work without a Tailwind run (pages are then unstyled).
package static

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"io/fs"
	"net/http"
	"strings"
	"sync"
)

//go:embed *.css *.js fonts
var files embed.FS

var (
	hashMu sync.Mutex
	hashes = map[string]string{}
)

// URL returns the asset path with a content-hash query ("/static/app.css?v=ab12…"),
// so a changed file is a new URL. Unknown or absent files get no query.
func URL(name string) string {
	hashMu.Lock()
	defer hashMu.Unlock()
	h, ok := hashes[name]
	if !ok {
		if b, err := files.ReadFile(name); err == nil {
			sum := sha256.Sum256(b)
			h = hex.EncodeToString(sum[:])[:12]
		}
		hashes[name] = h
	}
	if h == "" {
		return "/static/" + name
	}
	return "/static/" + name + "?v=" + h
}

// Handler serves the embedded files for paths under /static/. Hash-keyed URLs
// and fonts are immutable; anything else must revalidate. No directory listings.
func Handler() http.Handler {
	fileServer := http.FileServerFS(files)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		name := strings.TrimPrefix(r.URL.Path, "/static/")
		if name == "" || strings.HasSuffix(name, "/") {
			http.NotFound(w, r)
			return
		}
		if _, err := fs.Stat(files, name); err != nil {
			http.NotFound(w, r)
			return
		}
		if r.URL.Query().Get("v") != "" || strings.HasPrefix(name, "fonts/") {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		} else {
			w.Header().Set("Cache-Control", "no-cache")
		}
		r2 := r.Clone(r.Context())
		r2.URL.Path = "/" + name
		fileServer.ServeHTTP(w, r2)
	})
}
