// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
)

const countActiveAPITokens = `-- name: CountActiveAPITokens :one

SELECT COUNT(*) FROM api_token WHERE revoked_at IS NULL
`

// auth queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) CountActiveAPITokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAPITokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}
