// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: banners.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countImportReviewGames = `-- name: CountImportReviewGames :one

SELECT COUNT(*) FROM game WHERE import_review = 1
`

// Read-only queries for the list page, entry strips, tab visibility and global banners.
func (q *Queries) CountImportReviewGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImportReviewGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTagReviewQueue = `-- name: CountTagReviewQueue :one
SELECT COUNT(*) FROM tag_review tr WHERE tr.state IN ('pending', 'skipped')
  AND EXISTS (SELECT 1 FROM game_tag gt WHERE gt.game_id = tr.game_id AND gt.qualifier = 'present' AND gt.verification <> 'wrong' AND gt.removed_at_source_at IS NULL)
`

func (q *Queries) CountTagReviewQueue(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTagReviewQueue)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getF95CredentialHealth = `-- name: GetF95CredentialHealth :one
SELECT validity, tfa_trust_expires_at FROM f95_credential WHERE id = 1
`

type GetF95CredentialHealthRow struct {
	Validity          string
	TfaTrustExpiresAt sql.NullString
}

func (q *Queries) GetF95CredentialHealth(ctx context.Context) (GetF95CredentialHealthRow, error) {
	row := q.db.QueryRowContext(ctx, getF95CredentialHealth)
	var i GetF95CredentialHealthRow
	err := row.Scan(&i.Validity, &i.TfaTrustExpiresAt)
	return i, err
}

const listFilterTags = `-- name: ListFilterTags :many
SELECT t.id, t.slug, t.label, COUNT(DISTINCT gt.game_id) AS games
  FROM tag t
  JOIN game_tag gt ON gt.tag_id = t.id AND gt.verification <> 'wrong' AND gt.removed_at_source_at IS NULL
 GROUP BY t.id
 ORDER BY games DESC, t.label COLLATE NOCASE, t.id
`

type ListFilterTagsRow struct {
	ID    int64
	Slug  string
	Label string
	Games int64
}

// Tags the list filter can offer: those currently counted by the filter (not wrong, not removed at Source).
func (q *Queries) ListFilterTags(ctx context.Context) ([]ListFilterTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilterTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilterTagsRow
	for rows.Next() {
		var i ListFilterTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.Games,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
