// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package sqlcgen

import (
	"context"
)

const getLatestCheckRun = `-- name: GetLatestCheckRun :one

SELECT id, kind, started_at, finished_at, status, f95_stopped FROM check_run ORDER BY id DESC LIMIT 1
`

// checks queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) GetLatestCheckRun(ctx context.Context) (CheckRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestCheckRun)
	var i CheckRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.F95Stopped,
	)
	return i, err
}
