// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package sqlcgen

import (
	"context"
)

const getDownloadJob = `-- name: GetDownloadJob :one

SELECT id, game_id, source_id, target_version, "trigger", state, needs_human_reason, active_mirror_id, bytes_done, bytes_total, result_path, created_at, updated_at FROM download_job WHERE id = ?
`

// downloads queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) GetDownloadJob(ctx context.Context, id int64) (DownloadJob, error) {
	row := q.db.QueryRowContext(ctx, getDownloadJob, id)
	var i DownloadJob
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.SourceID,
		&i.TargetVersion,
		&i.Trigger,
		&i.State,
		&i.NeedsHumanReason,
		&i.ActiveMirrorID,
		&i.BytesDone,
		&i.BytesTotal,
		&i.ResultPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
