// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getGame = `-- name: GetGame :one

SELECT id, name, play_status, rating_x2, cover_path, cover_source_url, cover_fetched_at, platform_pref, import_review, added_at, updated_at FROM game WHERE id = ?
`

// games queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) GetGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlayStatus,
		&i.RatingX2,
		&i.CoverPath,
		&i.CoverSourceUrl,
		&i.CoverFetchedAt,
		&i.PlatformPref,
		&i.ImportReview,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGame = `-- name: InsertGame :one
INSERT INTO game (name, play_status, rating_x2, import_review, added_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, play_status, rating_x2, cover_path, cover_source_url, cover_fetched_at, platform_pref, import_review, added_at, updated_at
`

type InsertGameParams struct {
	Name         string
	PlayStatus   string
	RatingX2     sql.NullInt64
	ImportReview int64
	AddedAt      string
	UpdatedAt    string
}

func (q *Queries) InsertGame(ctx context.Context, arg InsertGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, insertGame,
		arg.Name,
		arg.PlayStatus,
		arg.RatingX2,
		arg.ImportReview,
		arg.AddedAt,
		arg.UpdatedAt,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlayStatus,
		&i.RatingX2,
		&i.CoverPath,
		&i.CoverSourceUrl,
		&i.CoverFetchedAt,
		&i.PlatformPref,
		&i.ImportReview,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBehindGameIDs = `-- name: ListBehindGameIDs :many
SELECT game_id FROM game_behind ORDER BY game_id
`

func (q *Queries) ListBehindGameIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listBehindGameIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var game_id int64
		if err := rows.Scan(&game_id); err != nil {
			return nil, err
		}
		items = append(items, game_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
