// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: importreview.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const listImportReviewGames = `-- name: ListImportReviewGames :many

SELECT g.id, g.name, g.play_status, s.dev_status,
       (SELECT COUNT(*) FROM play_log p WHERE p.game_id = g.id) AS play_log_count,
       lp.version AS last_played_version
  FROM game g
  LEFT JOIN source s ON s.game_id = g.id AND s.is_primary = 1
  LEFT JOIN game_last_played lp ON lp.game_id = g.id
 WHERE g.import_review = 1
 ORDER BY g.name COLLATE NOCASE, g.id
`

type ListImportReviewGamesRow struct {
	ID                int64
	Name              string
	PlayStatus        string
	DevStatus         sql.NullString
	PlayLogCount      int64
	LastPlayedVersion sql.NullString
}

// Read query for the import review list (R-CSV-10).
func (q *Queries) ListImportReviewGames(ctx context.Context) ([]ListImportReviewGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listImportReviewGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportReviewGamesRow
	for rows.Next() {
		var i ListImportReviewGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PlayStatus,
			&i.DevStatus,
			&i.PlayLogCount,
			&i.LastPlayedVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
