// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package sqlcgen

import (
	"context"
)

const getNotification = `-- name: GetNotification :one

SELECT id, kind, run_id, title, body, sent_at, error, created_at FROM notification WHERE id = ?
`

// notify queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) GetNotification(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RunID,
		&i.Title,
		&i.Body,
		&i.SentAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}
