// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlog.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertPlayLog = `-- name: InsertPlayLog :one

INSERT INTO play_log (game_id, version, played_on, origin, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, game_id, version, version_norm, played_on, origin, created_at
`

type InsertPlayLogParams struct {
	GameID    int64
	Version   string
	PlayedOn  sql.NullString
	Origin    string
	CreatedAt string
}

// playlog queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) InsertPlayLog(ctx context.Context, arg InsertPlayLogParams) (PlayLog, error) {
	row := q.db.QueryRowContext(ctx, insertPlayLog,
		arg.GameID,
		arg.Version,
		arg.PlayedOn,
		arg.Origin,
		arg.CreatedAt,
	)
	var i PlayLog
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Version,
		&i.VersionNorm,
		&i.PlayedOn,
		&i.Origin,
		&i.CreatedAt,
	)
	return i, err
}
