// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package sqlcgen

import (
	"context"
)

const getTagReview = `-- name: GetTagReview :one

SELECT game_id, state, last_reviewed_play_log_id, reviewed_at, updated_at FROM tag_review WHERE game_id = ?
`

// review queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) GetTagReview(ctx context.Context, gameID int64) (TagReview, error) {
	row := q.db.QueryRowContext(ctx, getTagReview, gameID)
	var i TagReview
	err := row.Scan(
		&i.GameID,
		&i.State,
		&i.LastReviewedPlayLogID,
		&i.ReviewedAt,
		&i.UpdatedAt,
	)
	return i, err
}
