// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSettings = `-- name: GetSettings :one

SELECT id, mirror_host_order, platform_pref, updated_at FROM settings WHERE id = 1
`

// settings queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.MirrorHostOrder,
		&i.PlatformPref,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertPlayStatuses = `-- name: ListAlertPlayStatuses :many
SELECT play_status FROM alert_play_status ORDER BY play_status
`

func (q *Queries) ListAlertPlayStatuses(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAlertPlayStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var play_status string
		if err := rows.Scan(&play_status); err != nil {
			return nil, err
		}
		items = append(items, play_status)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
