// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getPrimarySource = `-- name: GetPrimarySource :one
SELECT id, game_id, kind, is_primary, external_id, url, latest_version, change_key, latest_version_norm, dev_status, thread_updated_at, last_checked_at, last_detail_at, miss_count, details_pending, unavailable_at, unavailable_reason, checks_enabled, created_at FROM source WHERE game_id = ? AND is_primary = 1
`

func (q *Queries) GetPrimarySource(ctx context.Context, gameID int64) (Source, error) {
	row := q.db.QueryRowContext(ctx, getPrimarySource, gameID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Kind,
		&i.IsPrimary,
		&i.ExternalID,
		&i.Url,
		&i.LatestVersion,
		&i.ChangeKey,
		&i.LatestVersionNorm,
		&i.DevStatus,
		&i.ThreadUpdatedAt,
		&i.LastCheckedAt,
		&i.LastDetailAt,
		&i.MissCount,
		&i.DetailsPending,
		&i.UnavailableAt,
		&i.UnavailableReason,
		&i.ChecksEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertSource = `-- name: InsertSource :one

INSERT INTO source (game_id, kind, is_primary, external_id, url, latest_version, change_key, dev_status, thread_updated_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, game_id, kind, is_primary, external_id, url, latest_version, change_key, latest_version_norm, dev_status, thread_updated_at, last_checked_at, last_detail_at, miss_count, details_pending, unavailable_at, unavailable_reason, checks_enabled, created_at
`

type InsertSourceParams struct {
	GameID          int64
	Kind            string
	IsPrimary       int64
	ExternalID      sql.NullString
	Url             string
	LatestVersion   sql.NullString
	ChangeKey       sql.NullString
	DevStatus       sql.NullString
	ThreadUpdatedAt sql.NullString
	CreatedAt       string
}

// sources queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) InsertSource(ctx context.Context, arg InsertSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, insertSource,
		arg.GameID,
		arg.Kind,
		arg.IsPrimary,
		arg.ExternalID,
		arg.Url,
		arg.LatestVersion,
		arg.ChangeKey,
		arg.DevStatus,
		arg.ThreadUpdatedAt,
		arg.CreatedAt,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Kind,
		&i.IsPrimary,
		&i.ExternalID,
		&i.Url,
		&i.LatestVersion,
		&i.ChangeKey,
		&i.LatestVersionNorm,
		&i.DevStatus,
		&i.ThreadUpdatedAt,
		&i.LastCheckedAt,
		&i.LastDetailAt,
		&i.MissCount,
		&i.DetailsPending,
		&i.UnavailableAt,
		&i.UnavailableReason,
		&i.ChecksEnabled,
		&i.CreatedAt,
	)
	return i, err
}
