// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlcgen

import (
	"context"
)

const countSynonymsByOrigin = `-- name: CountSynonymsByOrigin :one
SELECT COUNT(*) FROM synonym WHERE origin = ?
`

func (q *Queries) CountSynonymsByOrigin(ctx context.Context, origin string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSynonymsByOrigin, origin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTagsByKind = `-- name: CountTagsByKind :one

SELECT COUNT(*) FROM tag WHERE kind = ?
`

// tags queries. The owning backlog item adds its queries to this file (see docs/spec/backlog.md).
func (q *Queries) CountTagsByKind(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTagsByKind, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}
